ERROR    processes.catalog:catalog.py:92 Unable to parse OCLC catalog record with id <MagicMock name='CatalogMapping().record.source_id' id='140591605006928'> due to