{"timestamp":1730402174255,"message":"Failed to get file contents from testURL","log.level":"ERROR","logger.name":"processes.file.s3_files","thread.id":139736933145472,"thread.name":"MainThread","process.id":2293,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/file/s3_files.py","line.number":118,"entity.type":"SERVICE","error.class":"builtins:Exception","error.message":""}
