{"timestamp":1729619823068,"message":"Unable to parse OCLC catalog record with id <MagicMock name='CatalogMapping().record.source_id' id='140097226064992'> due to ","log.level":"ERROR","logger.name":"processes.catalog","thread.id":140097892428672,"thread.name":"MainThread","process.id":2298,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/catalog.py","line.number":92,"entity.type":"SERVICE"}
