{"timestamp":1729691671473,"message":"Unable to get collection with id d902fd44-7cbe-4401-b50c-5b1bda8b1059","log.level":"ERROR","logger.name":"api.blueprints.drbCollection","thread.id":139779400858496,"thread.name":"MainThread","process.id":2361,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbCollection.py","line.number":290,"entity.type":"SERVICE","error.class":"builtins:Exception","error.message":"Database error"}
