ERROR    processes.oclcCatalog:oclcCatalog.py:88 Err querying OCLC Rec <MagicMock name='CatalogMapping().record.source_id' id='139796423678224'>