ERROR    processes.oclcCatalog:oclcCatalog.py:91 Unable to parse OCLC catalog record with id <MagicMock name='CatalogMapping().record.source_id' id='140410205117024'> due to