{"timestamp":1729088768991,"message":"Unable to get work with id a8512b02-779b-45c6-95a3-56f90831be46","log.level":"ERROR","logger.name":"api.blueprints.drbWork","thread.id":139748738403200,"thread.name":"MainThread","process.id":2469,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbWork.py","line.number":40,"entity.type":"SERVICE","error.class":"builtins:Exception","error.message":"Database error"}
