ERROR    api.blueprints.drbUtils:drbUtils.py:56 Unable to get total counts
Traceback (most recent call last):
  File "/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbUtils.py", line 52, in get_counts
    total_counts = db_client.fetchRowCounts()
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/unittest/mock.py", line 1092, in __call__
    return self._mock_call(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/unittest/mock.py", line 1096, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/unittest/mock.py", line 1151, in _execute_mock_call
    raise effect
Exception: Database error