ERROR    processes.sfrCluster:sfrCluster.py:104 Unable to cluster <MagicMock id='139797100119088'>